### ISSUE TITLE
KeyError: -1 on using Twitter Search API method with iterators

### ISSUE THREAD

**Issue by dansamara** [odrling/peony-twitter#20]
I am getting error "KeyError: -1" with code:

```python
request = client.api.search.tweets.get(q='nasa')
responses = request.iterator.with_max_id()

async for tweets in responses:
    pass
```

Traceback:
```
Traceback (most recent call last):
  File "/home/myhomedir/sent/file.py", line 26, in <module>
    loop.run_until_complete(get_home())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/myhomedir/sent/file.py", line 17, in get_home
    async for tweets in responses:
  File "/home/myhomedir/.virtualenvs/sent-R1T5iV79/lib/python3.6/site-packages/peony/iterators.py", line 60, in __anext__
    response = await self.call_on_response(response)
  File "/home/myhomedir/.virtualenvs/sent-R1T5iV79/lib/python3.6/site-packages/peony/iterators.py", line 90, in call_on_response
    self.kwargs[self.param] = response[-1]['id'] - 1
  File "/home/myhomedir/.virtualenvs/sent-R1T5iV79/lib/python3.6/site-packages/peony/data_processing.py", line 119, in __getitem__
    return self.data[key]
  File "/home/myhomedir/.virtualenvs/sent-R1T5iV79/lib/python3.6/site-packages/peony/data_processing.py", line 61, in __getitem__
    return super().__getitem__(key)
KeyError: -1
```

**Comment by odrling** [comment]
The iterator only worked with userstreams, and the responses' format of the search API is different. 
I'll have to check check how all the endpoints reply.
For now the master branch should work fine for the search API.

**Comment by dansamara** [comment]
it's amazing!
Thanks for your work!

**Comment by odrling** [comment]
It's now in the new release (1.1.2)
