### ISSUE TITLE
Getting peony.exceptions.NotFound: b''

### ISSUE THREAD

**Issue by razaqq** [odrling/peony-twitter#23]
Im using the EventStream example from the docs.
Im using python 3.7

```Traceback (most recent call last):
  File "<>\main.py", line 55, in <module>
    client.run()
  File "<>\venv\lib\site-packages\peony\client.py", line 421, in run
    self.loop.run_until_complete(self.arun())
  File "<>\venv\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "<>\venv\lib\site-packages\peony\client.py", line 413, in arun
    await self.run_tasks()
  File "<>\venv\lib\site-packages\peony\client.py", line 407, in run_tasks
    await self._gathered_tasks
  File "<>\venv\lib\site-packages\peony\commands\event_handlers.py", line 80, in start
    async for data in resource:
  File <>\venv\lib\site-packages\peony\stream.py", line 144, in __anext__
    await self.connect()
  File "<>\venv\lib\site-packages\peony\stream.py", line 123, in connect
    url=self.kwargs['url'])
  File "<>\venv\lib\site-packages\peony\exceptions.py", line 36, in throw
    raise exception(response=response, data=data, **kwargs)
peony.exceptions.NotFound: b''
url: https://userstream.twitter.com/1.1/user.json```

**Comment by odrling** [comment]
Twitter closed the userstream API last year, so I can't do much about that except remove the examples from the docs.

**Comment by razaqq** [comment]
Is there still a way to stream the Tweets of a person with this lib?

**Comment by odrling** [comment]
Yes, the stream API is still here: https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html.

With peony it should be `client.stream.statuses.filter.post(follow=user_ids)`.
