### ISSUE TITLE
Annoying "Task exception was never retrieved" warning when oauth setup fails

### ISSUE THREAD

**Issue by arlyon** [odrling/peony-twitter#30]
Exceptions from `oauth_dance` and `async_oauth_dance` produce an annoying warning:

```
Task exception was never retrieved
future: <Task finished coro=<ErrorHandler.__call__() done, defined at /Users/arlyon/Library/Caches/pypoetry/virtualenvs/hyperion-wffnBiT2-py3.7/lib/python3.7/site-packages/peony/utils.py:91> exception=NotAuthenticated('Could not authenticate you.\nurl: https://api.twitter.com/oauth/request_token')>
Traceback (most recent call last):
  File "/Users/arlyon/Library/Caches/pypoetry/virtualenvs/hyperion-wffnBiT2-py3.7/lib/python3.7/site-packages/peony/utils.py", line 108, in __call__
    raise exc
  File "/Users/arlyon/Library/Caches/pypoetry/virtualenvs/hyperion-wffnBiT2-py3.7/lib/python3.7/site-packages/peony/utils.py", line 97, in __call__
    return await self.__request(future=future, **kwargs)
  File "/Users/arlyon/Library/Caches/pypoetry/virtualenvs/hyperion-wffnBiT2-py3.7/lib/python3.7/site-packages/peony/client.py", line 345, in request
    encoding=encoding, url=url)
  File "/Users/arlyon/Library/Caches/pypoetry/virtualenvs/hyperion-wffnBiT2-py3.7/lib/python3.7/site-packages/peony/exceptions.py", line 31, in throw
    raise exception(response=response, error=error, data=data, **kwargs)
peony.exceptions.NotAuthenticated: Could not authenticate you.
url: https://api.twitter.com/oauth/request_token
```

Here is a minimal repl.it to illustrate:

https://repl.it/repls/GiftedRundownAmoeba

I am still not able to track down exactly why, even after a few hours (otherwise there'd be a PR waiting).

**Comment by odrling** [comment]
Found it, seems like I was sending an exception into the void

Thanks for reporting

**Comment by arlyon** [comment]
Missed this, thanks!
