### ISSUE TITLE
seeing `Task exception was never retrieved` from the `asyncio` logger

### ISSUE THREAD

**Issue by gertvdijk** [odrling/peony-twitter#37]
I'm relatively new to async programming in Python, so it could be just me doing something stupid, but I think I've hit a bug in Peony. I'd appreciate some advice.

Using Peony in an async FastAPI function, I'm seeing `Task exception was never retrieved` from the `asyncio` logger. Here's a minimal example in which I try to catch the HTTP forbidden error on a suspended account retrieval and handle it nicely.

```python
@app.get("/peony-repl-bug")
async def peony_repl_bug():
    peony_client = peony.PeonyClient(**twitter_creds)
    try:
        # Known suspended user account, expected to raise peony.exceptions.Forbidden
        result = await asyncio.gather(peony_client.api.users.show.get(screen_name="realDonaldTrump"))
    except peony.exceptions.Forbidden as e:
        logger.info("exception info: %r" % e)
        raise HTTPException(status_code=503, detail="Unhandled exception")
    else:
        logger.info(result[0])
```

Calling it results in catching the exception (lines 3+4 below are expected :heavy_check_mark:) *as well as* the asyncio errors (below `ERROR:asyncio:Task exception was never retrieved` :negative_squared_cross_mark:).

It seems like a bug in Peony to me, no?

```
INFO:peony.data_processing:decoding data as json
INFO:peony.data_processing:decoding data as json
INFO:myproject.web:exception info: Forbidden("{'errors': [{'code': 63, 'message': 'User has been suspended.'}]}\nurl: https://api.twitter.com/1.1/users/show.json")
INFO:     127.0.0.1:60554 - "GET /peony-repl-bug HTTP/1.1" 503 Service Unavailable
INFO:peony.data_processing:decoding data as json
INFO:peony.data_processing:decoding data as json
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<ErrorHandler.__call__() done, defined at /path/to/myvenv/lib/python3.8/site-packages/peony/utils.py:91> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/path/to/myvenv/lib/python3.8/site-packages/peony/utils.py", line 97, in __call__
    return await self.__request(future=future, **kwargs)
  File "/path/to/myvenv/lib/python3.8/site-packages/peony/client.py", line 344, in request
    await exceptions.throw(response, loads=self._loads,
  File "/path/to/myvenv/lib/python3.8/site-packages/peony/exceptions.py", line 35, in throw
    raise exception(response=response, data=data, **kwargs)
peony.exceptions.Forbidden: {'errors': [{'code': 63, 'message': 'User has been suspended.'}]}
url: https://api.twitter.com/1.1/users/show.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/myvenv/lib/python3.8/site-packages/peony/utils.py", line 106, in __call__
    future.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
```

This also happens with `return_exceptions=True` in the `asyncio.gather()` or with a plain `await` on the coroutine.
```python
result = await peony_client.api.users.show.get(screen_name="realDonaldTrump")
```

Python 3.8.0 as in Ubuntu Bionic (`python3.8`), `peony-twitter` 1.1.7 from PyPI, FastAPI 0.63.0.

Thanks! :pray:

**Comment by gertvdijk** [comment]
Quick testing shows this seems to work with 02baf7157441e364ad58191a497608b4c40897cd! Thank you so much for the quick response to this, much appreciated. :+1:

**Comment by odrling** [comment]
Oh I was about to ask you to try it out since I wasn't able to reproduce this error.
Great!

**Comment by noahkw** [comment]
Hi, 

I keep running into a similar error with the following code:
```python
        try:
            tweet = await self.client.api.statuses.show.get(
                id=tweet_id, include_entities=True, tweet_mode="extended"
            )
        except peony.exceptions.NotFound:
            return None

        return tweet
```

Exception:

```
2021-05-22 19:04:54,167:ERROR:asyncio: Task exception was never retrieved
future: <Task finished name='Task-60' coro=<ErrorHandler.__call__() done, defined at /home/noah/workspace/botw-bot/venv/lib/python3.9/site-packages/peony/utils.py:91> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/noah/workspace/botw-bot/venv/lib/python3.9/site-packages/peony/utils.py", line 97, in __call__
    return await self.__request(future=future, **kwargs)
  File "/home/noah/workspace/botw-bot/venv/lib/python3.9/site-packages/peony/client.py", line 344, in request
    await exceptions.throw(response, loads=self._loads,
  File "/home/noah/workspace/botw-bot/venv/lib/python3.9/site-packages/peony/exceptions.py", line 35, in throw
    raise exception(response=response, data=data, **kwargs)
peony.exceptions.NotFound: {'errors': [{'code': 144, 'message': 'No status found with that ID.'}]}
url: https://api.twitter.com/1.1/statuses/show.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/noah/workspace/botw-bot/venv/lib/python3.9/site-packages/peony/utils.py", line 107, in __call__
    future.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
```

I managed to circumvent this by doing the following, but I don't know whether this breaks any tests because I can't run them on master~17. One of them hangs indefinitely and a few fail (without any changes).

```diff
diff --git a/peony/utils.py b/peony/utils.py
index 37f539c..978cdb9 100644
--- a/peony/utils.py
+++ b/peony/utils.py
@@ -108,10 +108,10 @@ class ErrorHandler(metaclass=MetaErrorHandler):
 
                 if status is ErrorHandler.RAISE:
                     _logger.debug("raising exception")
-                    if future is not None:
+                    if future and not future.done():
                         future.set_exception(exc)
                     else:
-                        raise exc
+                        return
 
 
 class DefaultErrorHandler(ErrorHandler):
```

**Comment by odrling** [comment]
Did you install peony from git, it should have worked fine starting from 02baf71 and I don't get how it would run future.set_exception starting from this commit.
The `raise exc` is useful too so we can't replace it by `return`.
I'm working on getting the tests to pass again, not exactly sure how it got so bad.

**Comment by noahkw** [comment]
That seems to have worked. Thanks.
