### ISSUE TITLE
Problems with search api authorization

### ISSUE THREAD

**Issue by alex4321** [odrling/peony-twitter#4]
Inside my script I use code like next:

```
self.peony = PeonyClient(consumer_key, consumer_secret, access_token, access_token_secret)
...
params = {
       "q": quote(request),
       "count": 100,
}
response = self.peony.api.search.tweets.get(**params)
```
Seems like it not works for some reqests.
E.g. - for ```request='Warson'``` it return response with tweets.
For ```request='Watson AND IBM'``` - it raise error ```peony.exceptions.Unauthorized: Could not authenticate you.```
Same for ```request=urllib.request.quote('Watson AND IBM')```

**Comment by odrling** [comment]
You don't have to use `urllib.request.quote`. It seems like aiohttp does it for us.

**Comment by alex4321** [comment]
Anyway - it gives same result for both cases.
Maybe in next few hours I'll try to make minimal sample of code that reproduce error.

**Comment by alex4321** [comment]
E.g I have script

```
from peony import PeonyClient
import asyncio


async def main():
    peony = PeonyClient("ConsumerId",
                        "ConsumerSecret",
                        "AccessToken",
                        "AccessTokenSecret")
    print(await peony.api.search.tweets.get(q="AAPL"))


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

It'll show correct response
```
{'search_metadata': {'refresh_url': ...
```

But 
```
from peony import PeonyClient
import asyncio


async def main():
    peony = PeonyClient("ConsumerId",
                        "ConsumerSecret",
                        "AccessToken",
                        "AccessTokenSecret")
    print(await peony.api.search.tweets.get(q="$AAPL"))


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

Raises exceptions:
```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/twitter-classifier/demo.py", line 14, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/user/PycharmProjects/twitter-classifier/demo.py", line 10, in main
    print(await peony.api.search.tweets.get(q="$AAPL"))
  File "/home/user/Документы/venv/twitter-classifier/lib/python3.5/site-packages/peony/utils.py", line 131, in decorated_request
    return await request(**kwargs)
  File "/home/user/Документы/venv/twitter-classifier/lib/python3.5/site-packages/peony/client.py", line 284, in request
    await exceptions.throw(response)
  File "/home/user/Документы/venv/twitter-classifier/lib/python3.5/site-packages/peony/exceptions.py", line 39, in throw
    raise exception(response=response, data=data, **kwargs)
peony.exceptions.Unauthorized: Could not authenticate you.
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f0f8170be48>
transport: <_SelectorSocketTransport fd=7>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f0f8170be48>
transport: <_SelectorSocketTransport closing fd=7>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 632, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 704, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 589, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 601, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by odrling** [comment]
Okay I pushed a commit with a new way to create the Authentication header. It seems like this `q` parameter has to be handled differently from all the others parameters.

So now it should work with queries containing '$' or ':' or '!' or '?'. I'm still not sure if these are the only characters that cause this error.
